### ISSUE TITLE
New feature branch autoload

### ISSUE THREAD

**Issue by navjottomer** [navjottomer/Osclass#153]
### Created a new branch: [autoload](https://github.com/navjottomer/Osclass/tree/autoload)

Need testing that everything is working as expected. In this branch, I restructured osclass core and added an autoloader to automatically load osclass classes, will increase some maintainability. I hope these changes will fix unwanted fatal errors, related to osclass classes loading with other benefits of autoloading.
In my testing, osclass was working fine but need approval from community members.
Please test this branch and let me know about any issue with these changes. Or you can suggest other changes in this branch.
Will merge this into develop after testing.
**Please keep the non-development discussion to our support forum**
**https://osclass.discourse.group/t/new-feature-branch-autoload/40**

**Comment by eurobank** [comment]
Since i have no idea what that means, can you tell me in two lines what should i search for when testing?

**Comment by web-media** [comment]
the script not installing . something wrong with autoload branch

**Comment by web-media** [comment]
Warning: Use of undefined constant WEB_PATH - assumed 'WEB_PATH' (this will throw an Error in a future version of PHP) in N:\a\htdocs\autoload\oc-includes\osclass\default-constants.php on line 40

**Comment by navjottomer** [comment]
@web-media Thanks for testing, pushed some changes. Installation is working now. Please check again.
`Warning: Use of undefined constant WEB_PATH - assumed 'WEB_PATH' (this will throw an Error in a future version of PHP) in N:\a\htdocs\autoload\oc-includes\osclass\default-constants.php on line 40`
Where did you get these notices and warning? Steps to reproduce these issue?

@eurobank Please search for any php notices or error in logs, while testing every functionality of osclass you can.

**Comment by web-media** [comment]
```php
ini_set('display_errors', 1);
    error_reporting(E_ALL | E_STRICT); 
```
on install.php

**Comment by eurobank** [comment]
Uploading this branch to an existing 3.9, i see these errors today. 

> [30-Nov-2019 21:15:20 Europe/Madrid] PHP Warning:  Illegal string offset 'pk_i_id' in /home/oc-content/themes/bender/search-sidebar.php on line 23
> [30-Nov-2019 21:15:20 Europe/Madrid] PHP Warning:  Cannot assign an empty string to a string offset in /home/oc-content/themes/bender/search-sidebar.php on line 23
> [30-Nov-2019 21:15:20 Europe/Madrid] PHP Warning:  Illegal string offset 'pk_i_id' in /home/oc-content/themes/bender/search-sidebar.php on line 91
> [30-Nov-2019 21:15:20 Europe/Madrid] PHP Notice:  Uninitialized string offset: 0 in /home/oc-content/themes/bender/search-sidebar.php on line 91
> [01-Dec-2019 08:32:56 Europe/Madrid] PHP Warning:  Illegal string offset 'pk_i_id' in /home/oc-content/themes/bender/search-sidebar.php on line 23
> [01-Dec-2019 08:32:56 Europe/Madrid] PHP Warning:  Cannot assign an empty string to a string offset in /home/oc-content/themes/bender/search-sidebar.php on line 23
> [01-Dec-2019 08:32:56 Europe/Madrid] PHP Warning:  Illegal string offset 'pk_i_id' in /home/oc-content/themes/bender/search-sidebar.php on line 91
> [01-Dec-2019 08:32:56 Europe/Madrid] PHP Notice:  Uninitialized string offset: 0 in /home/oc-content/themes/bender/search-sidebar.php on line 91

**Comment by navjottomer** [comment]
@eurobank this is a bender issue nothing related to osclass itself, use latest master branch https://github.com/navjottomer/theme-bender

**Comment by eurobank** [comment]
Sure, but those errors weren't there with before i uploaded this branch. So logically they could be related.

**Comment by navjottomer** [comment]
@eurobank I don't know why you get these errors with this branch only ( There could be hundreds of reason) but they are bender theme issues. I already pushed an update in bender-theme, also updated this branch to use that version.

@web-media I have pushed some more fixes, those warnings are gone now. Check for other errors.

**Comment by web-media** [comment]
installed after few tries .  first try got  stuck  on step 2 where introducing  admin  and site info .
second and 3rd try work well .

**Comment by web-media** [comment]
**Item Page** 
 autoload    memory: 6.9071655273438 MiB load time : 0.11014080047607 seconds 
 osclass390 memory: 8.0103530883789 MiB load time : 0.17194485664368 seconds 
**Search Page**
 autoload Memory: 6.8277282714844 MiB LoadTime: 0.14181205749512 seconds 
osclass390Memory: 8.0421981811523 MiB LoadTime: 0.15677499771118 seconds 
**Contact** 
autoload    Memory: 5.7218246459961 MiB LoadTime: 0.11008787155151 seconds 
osclass390 Memory: 7.7084274291992 MiB LoadTime: 0.12513399124146 seconds 
There some good improvements .

**Comment by web-media** [comment]
An issue .. location still not ordered by name . Spain is between ecuador and finland
![Capture](https://user-images.githubusercontent.com/5124319/69919681-e1357300-147f-11ea-9191-662d19495b53.PNG)

**Comment by eurobank** [comment]
@web-media apparently the sorting is by the "value" and not the name of country.

**Comment by navjottomer** [comment]
Sorting is done as per file name while creating list.json file with this script https://github.com/navjottomer/Osclass-Extras/blob/master/locations/dir2json.py
I need to fix that.

**Comment by navjottomer** [comment]
Closing this issue, this branch is merged in develop. BTW I also fixed that sorting issue [984cb603426a6a94c621d886305147dee8d9c28c](https://github.com/navjottomer/Osclass-Extras/commit/984cb603426a6a94c621d886305147dee8d9c28c)
